spring:
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: '1000'
        format_sql: 'false'
        show_sql: 'true'
    defer-datasource-initialization: 'true'
    hibernate:
      ddl-auto: update
  datasource:
    data: classpath:data.sql
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: never
    username: root
    url: jdbc:mysql://3.34.130.154:3306/mysql
    sql-script-encoding: UTF-8
  h2:
    console:
      path: /h2-console
      enabled: 'true'
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        SQL: DEBUG
